name: Docker Build Image

on:
  workflow_dispatch:
    inputs:
      IMAGE_VERSION:
        description: 'Image version'
        required: true
        default: 'latest'
      IMAGE_NAME:
        description: 'Image name'
        required: true
      DOCKERFILE_NAME:
        description: 'Dockerfile name'
        required: true
        default: 'Dockerfile'
      PLATFORMS:
        description: 'Build platforms'
        required: false
        default: 'linux/amd64,linux/arm64'
      REGISTRY_ADDR:
        description: 'Registry address'
        required: false
        default: 'ghcr.io'
      REGISTRY_TYPE:
        description: 'Registry type (dockerhub, ghcr)'
        required: true
        default: 'ghcr'
      REGISTRY_USER:
        description: 'Registry user'
        required: true

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        if: github.event.inputs.REGISTRY_TYPE == 'dockerhub'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Login to GitHub Container Registry
        if: github.event.inputs.REGISTRY_TYPE == 'ghcr'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push Docker image
        env:
          IMAGE_VERSION: ${{ github.event.inputs.IMAGE_VERSION }}
          REGISTRY_ADDR: ${{ github.event.inputs.REGISTRY_ADDR }}
          REGISTRY_USER: ${{ github.event.inputs.REGISTRY_USER }}
          IMAGE_NAME: ${{ github.event.inputs.IMAGE_NAME }}
          DOCKERFILE_NAME: ${{ github.event.inputs.DOCKERFILE_NAME }}
          PLATFORMS: ${{ github.event.inputs.PLATFORMS }}
        run: |
          make build-image IMAGE_VERSION=$IMAGE_VERSION REGISTRY_ADDR=$REGISTRY_ADDR REGISTRY_USER=$REGISTRY_USER IMAGE_NAME=$IMAGE_NAME DOCKERFILE_NAME=$DOCKERFILE_NAME PLATFORMS=$PLATFORMS