name: Docker Image Build and Push

on:
  workflow_dispatch:
    inputs:
      DOCKERFILE_NAME:
        description: 'Name of the Dockerfile to use (e.g., Dockerfile-alpine, Dockerfile-busybox)'
        required: true
        default: 'Dockerfile'
      IMAGE_VERSION:
        description: 'Version of the image to build'
        required: false
        default: 'latest'
      BUILDER_NAME:
        description: 'Name of the buildx builder'
        required: false
        default: 'my-image-builder'
      REGISTRY_URI:
        description: 'URI of the Docker registry'
        required: true
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REGISTRY_URI }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Set IMAGE_NAME based on Dockerfile
        id: set-image-name
        run: |
          DOCKERFILE=${{ github.event.inputs.DOCKERFILE_NAME }}
          IMAGE_NAME=$(echo $DOCKERFILE | cut -d'-' -f2)
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        run: |
          make IMAGE_VERSION=${{ github.event.inputs.IMAGE_VERSION }} \
               BUILDER_NAME=${{ github.event.inputs.BUILDER_NAME }} \
               REGISTRY_URI=${{ github.event.inputs.REGISTRY_URI }} \
               DOCKERFILE_NAME=${{ github.event.inputs.DOCKERFILE_NAME }} \
               IMAGE_NAME=${{ steps.set-image-name.outputs.IMAGE_NAME }}

      - name: Clean up buildx builder
        run: make clean    
